-- Cache tables for PO module - replicate EBS structure with LAST_UPDATE_DATE for watermarking

-- PO_HEADERS_ALL cache
CREATE TABLE PO_HEADERS_ALL (
    PO_HEADER_ID NUMBER PRIMARY KEY,
    SEGMENT1 VARCHAR2(20),
    SEGMENT2 VARCHAR2(20),
    SEGMENT3 VARCHAR2(20),
    SEGMENT4 VARCHAR2(20),
    SEGMENT5 VARCHAR2(20),
    VENDOR_ID NUMBER,
    VENDOR_SITE_ID NUMBER,
    PO_DATE DATE,
    CREATION_DATE DATE,
    CREATED_BY NUMBER,
    LAST_UPDATE_DATE DATE,
    LAST_UPDATED_BY NUMBER,
    CLOSED_DATE DATE,
    CLOSED_CODE VARCHAR2(25),
    STATUS VARCHAR2(1),
    TYPE_LOOKUP_CODE VARCHAR2(25),
    CURRENCY_CODE VARCHAR2(15),
    APPROVAL_STATUS VARCHAR2(30),
    REVISION_NUM NUMBER,
    AGENT_ID NUMBER,
    ORG_ID NUMBER,
    COMMENTS VARCHAR2(2000),
    AUTHORIZATION_STATUS VARCHAR2(1),
    QUOTE_VENDOR_QUOTE_NUMBER VARCHAR2(256),
    QUOTE_EXPIRES_DATE DATE,
    QUOTE_CREATION_DATE DATE,
    QUOTATION_CLASS_CODE VARCHAR2(30),
    START_DATE DATE,
    END_DATE DATE
);

CREATE INDEX IDX_PO_HDR_LAST_UPD ON PO_HEADERS_ALL(LAST_UPDATE_DATE);
CREATE INDEX IDX_PO_HDR_VENDOR ON PO_HEADERS_ALL(VENDOR_ID);

-- PO_LINES_ALL cache
CREATE TABLE PO_LINES_ALL (
    PO_LINE_ID NUMBER PRIMARY KEY,
    PO_HEADER_ID NUMBER NOT NULL,
    LINE_NUM NUMBER,
    LINE_TYPE_ID NUMBER,
    ITEM_ID NUMBER,
    ITEM_DESCRIPTION VARCHAR2(1000),
    UNIT_MEAS_LOOKUP_CODE VARCHAR2(25),
    UNIT_PRICE NUMBER,
    QUANTITY NUMBER,
    AMOUNT NUMBER,
    CREATION_DATE DATE,
    CREATED_BY NUMBER,
    LAST_UPDATE_DATE DATE,
    LAST_UPDATED_BY NUMBER,
    CLOSED_CODE VARCHAR2(25),
    CLOSED_DATE DATE,
    CANCEL_FLAG VARCHAR2(1),
    CANCEL_DATE DATE,
    CANCELLED_BY NUMBER,
    LINE_STATUS_ID NUMBER,
    AUCTION_HEADER_ID NUMBER,
    SUPPLIER_REF_NUMBER VARCHAR2(50)
);

CREATE INDEX IDX_PO_LINES_LAST_UPD ON PO_LINES_ALL(LAST_UPDATE_DATE);
CREATE INDEX IDX_PO_LINES_PO_HDR ON PO_LINES_ALL(PO_HEADER_ID);

-- GL_CODE_COMBINATIONS cache
CREATE TABLE GL_CODE_COMBINATIONS (
    CODE_COMBINATION_ID NUMBER PRIMARY KEY,
    CHART_OF_ACCOUNTS_ID NUMBER,
    SEGMENT1 VARCHAR2(25),
    SEGMENT2 VARCHAR2(25),
    SEGMENT3 VARCHAR2(25),
    SEGMENT4 VARCHAR2(25),
    SEGMENT5 VARCHAR2(25),
    SEGMENT6 VARCHAR2(25),
    SEGMENT7 VARCHAR2(25),
    SEGMENT8 VARCHAR2(25),
    SEGMENT9 VARCHAR2(25),
    SEGMENT10 VARCHAR2(25),
    CREATION_DATE DATE,
    CREATED_BY NUMBER,
    LAST_UPDATE_DATE DATE,
    LAST_UPDATED_BY NUMBER,
    ENABLED_FLAG VARCHAR2(1),
    SUMMARY_FLAG VARCHAR2(1),
    DETAIL_POSTING_ALLOWED_FLAG VARCHAR2(1)
);

CREATE INDEX IDX_GL_CC_LAST_UPD ON GL_CODE_COMBINATIONS(LAST_UPDATE_DATE);
CREATE INDEX IDX_GL_CC_SEGMENT1 ON GL_CODE_COMBINATIONS(SEGMENT1);

-- PO_DISTRIBUTIONS_ALL cache
CREATE TABLE PO_DISTRIBUTIONS_ALL (
    PO_DISTRIBUTION_ID NUMBER PRIMARY KEY,
    PO_HEADER_ID NUMBER NOT NULL,
    PO_LINE_ID NUMBER NOT NULL,
    LINE_LOCATION_ID NUMBER NOT NULL,
    DISTRIBUTION_NUM NUMBER,
    QUANTITY_ORDERED NUMBER,
    QUANTITY_DELIVERED NUMBER,
    QUANTITY_CANCELLED NUMBER,
    QUANTITY_BILLED NUMBER,
    AMOUNT_ORDERED NUMBER,
    AMOUNT_DELIVERED NUMBER,
    AMOUNT_BILLED NUMBER,
    CREATION_DATE DATE,
    CREATED_BY NUMBER,
    LAST_UPDATE_DATE DATE,
    LAST_UPDATED_BY NUMBER,
    CODE_COMBINATION_ID NUMBER,
    ORG_ID NUMBER,
    DISTRIBUTION_ACCOUNT_ID NUMBER,
    MATCH_OPTION VARCHAR2(2),
    DESTINATION_TYPE_CODE VARCHAR2(25),
    DESTINATION_ORGANIZATION_ID NUMBER,
    DESTINATION_SUBINVENTORY VARCHAR2(10),
    REASON_DISPUTED_FLAG VARCHAR2(1),
    FINALLY_CLOSED_FLAG VARCHAR2(1)
);

CREATE INDEX IDX_PO_DIST_LAST_UPD ON PO_DISTRIBUTIONS_ALL(LAST_UPDATE_DATE);
CREATE INDEX IDX_PO_DIST_PO_HDR ON PO_DISTRIBUTIONS_ALL(PO_HEADER_ID);
CREATE INDEX IDX_PO_DIST_PO_LINE ON PO_DISTRIBUTIONS_ALL(PO_LINE_ID);

-- PO_LINE_LOCATIONS_ALL cache
CREATE TABLE PO_LINE_LOCATIONS_ALL (
    LINE_LOCATION_ID NUMBER PRIMARY KEY,
    PO_HEADER_ID NUMBER NOT NULL,
    PO_LINE_ID NUMBER NOT NULL,
    LOCATION_ID NUMBER,
    QUANTITY_ORDERED NUMBER,
    QUANTITY_DELIVERED NUMBER,
    QUANTITY_CANCELLED NUMBER,
    QUANTITY_BILLED NUMBER,
    UNIT_MEAS_LOOKUP_CODE VARCHAR2(25),
    UNIT_PRICE NUMBER,
    AMOUNT NUMBER,
    CREATION_DATE DATE,
    CREATED_BY NUMBER,
    LAST_UPDATE_DATE DATE,
    LAST_UPDATED_BY NUMBER,
    CLOSED_CODE VARCHAR2(25),
    CLOSED_DATE DATE,
    CANCEL_FLAG VARCHAR2(1),
    CANCEL_DATE DATE,
    CANCELLED_BY NUMBER,
    SHIPMENT_NUM NUMBER,
    SHIPMENT_TYPE VARCHAR2(25),
    NEED_BY_DATE DATE,
    PRICE_OVERRIDE_FLAG VARCHAR2(1),
    TAX_CODE_ID NUMBER,
    MATCH_OPTION VARCHAR2(2)
);

CREATE INDEX IDX_PO_LL_LAST_UPD ON PO_LINE_LOCATIONS_ALL(LAST_UPDATE_DATE);
CREATE INDEX IDX_PO_LL_PO_HDR ON PO_LINE_LOCATIONS_ALL(PO_HEADER_ID);
CREATE INDEX IDX_PO_LL_PO_LINE ON PO_LINE_LOCATIONS_ALL(PO_LINE_ID);
