-- Control table for PO cache load orchestration
-- Tracks state, watermarks, and metrics per cache table
CREATE TABLE PO_CACHE_LOAD_CONTROL (
    TABLE_NAME VARCHAR2(30) PRIMARY KEY,
    LOAD_TYPE VARCHAR2(20),
    LAST_EXTRACT_DATE TIMESTAMP,
    LAST_RUN_START TIMESTAMP,
    LAST_RUN_END TIMESTAMP,
    STATUS VARCHAR2(20),
    ROWS_READ NUMBER,
    ROWS_MERGED NUMBER,
    ERROR_MESSAGE VARCHAR2(4000),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    MODIFIED_DATE TIMESTAMP DEFAULT SYSDATE
);

-- Initialize control rows for all cache tables
INSERT INTO PO_CACHE_LOAD_CONTROL (TABLE_NAME, LOAD_TYPE, STATUS)
VALUES ('PO_HEADERS_ALL', 'INCREMENTAL', 'PENDING');

INSERT INTO PO_CACHE_LOAD_CONTROL (TABLE_NAME, LOAD_TYPE, STATUS)
VALUES ('PO_LINES_ALL', 'INCREMENTAL', 'PENDING');

INSERT INTO PO_CACHE_LOAD_CONTROL (TABLE_NAME, LOAD_TYPE, STATUS)
VALUES ('GL_CODE_COMBINATIONS', 'INCREMENTAL', 'PENDING');

INSERT INTO PO_CACHE_LOAD_CONTROL (TABLE_NAME, LOAD_TYPE, STATUS)
VALUES ('PO_DISTRIBUTIONS_ALL', 'INCREMENTAL', 'PENDING');

INSERT INTO PO_CACHE_LOAD_CONTROL (TABLE_NAME, LOAD_TYPE, STATUS)
VALUES ('PO_LINE_LOCATIONS_ALL', 'INCREMENTAL', 'PENDING');

COMMIT;
